# Generated by Django 4.0.2 on 2022-02-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=20, unique=True, verbose_name='Uniq ID')),
                ('car_category', models.CharField(max_length=2, verbose_name='Car category')),
                ('brand_id', models.CharField(max_length=20, verbose_name='Brand ID')),
                ('year_from', models.DateField(verbose_name='Year from')),
                ('year_to', models.DateField(verbose_name='Year to')),
                ('brand', models.CharField(max_length=25, verbose_name='Brand of car')),
                ('mark_id', models.CharField(max_length=25, verbose_name='Mark ID')),
                ('mark', models.CharField(max_length=25, verbose_name='Mark')),
                ('cyrillic_mark', models.CharField(max_length=25, verbose_name='Mark name in russia')),
                ('model', models.CharField(max_length=25, verbose_name='Model of car')),
                ('cyrillic_model', models.CharField(max_length=25, verbose_name='Model name in russia')),
                ('eng_power', models.IntegerField(verbose_name='Engine Power')),
                ('horse_power', models.IntegerField(verbose_name='Horse Power')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
